version: '3.8'
services:
  trysqlite:
    build: .
    container_name: trysqlite-app
    ports:
      - "80:5000"
    volumes:
      - ./instance:/app/instance
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    restart: unless-stopped
