"""Add PdfTemplate model

Revision ID: 311cd11f7316
Revises: 12e626fac898
Create Date: 2025-05-21 13:20:26.209393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311cd11f7316'
down_revision = '12e626fac898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pdf_template')
    # ### end Alembic commands ###
