"""Firmendaten-Modell

Revision ID: 62cd2b516ba2
Revises: 99d2e7a38f0d
Create Date: 2025-05-20 20:05:40.131215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62cd2b516ba2'
down_revision = '99d2e7a38f0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('street', sa.String(length=128), nullable=True),
    sa.Column('house_number', sa.String(length=16), nullable=True),
    sa.Column('postal_code', sa.String(length=16), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('uid', sa.String(length=32), nullable=True),
    sa.Column('firmenbuchnummer', sa.String(length=32), nullable=True),
    sa.Column('wirtschaftskammer', sa.String(length=128), nullable=True),
    sa.Column('iban', sa.String(length=64), nullable=True),
    sa.Column('bic', sa.String(length=32), nullable=True),
    sa.Column('bank', sa.String(length=128), nullable=True),
    sa.Column('logo_filename', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('website', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_settings')
    # ### end Alembic commands ###
