"""Add color settings to company

Revision ID: 6d91f6c50b7c
Revises: c4e9be8eb442
Create Date: 2025-05-24 13:15:34.546977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d91f6c50b7c'
down_revision = 'c4e9be8eb442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_settings', sa.Column('primary_color', sa.String(length=7), nullable=True))
    op.add_column('company_settings', sa.Column('secondary_color', sa.String(length=7), nullable=True))
    op.add_column('company_settings', sa.Column('accent_color', sa.String(length=7), nullable=True))
    op.add_column('company_settings', sa.Column('text_color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_settings', 'text_color')
    op.drop_column('company_settings', 'accent_color')
    op.drop_column('company_settings', 'secondary_color')
    op.drop_column('company_settings', 'primary_color')
    # ### end Alembic commands ###
