"""add_number_prefixes_to_company_settings

Revision ID: c4e9be8eb442
Revises: cba884fb1c2c
Create Date: 2025-05-23 15:12:01.175426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e9be8eb442'
down_revision = 'cba884fb1c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offer_number_prefix', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('invoice_number_prefix', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.drop_column('invoice_number_prefix')
        batch_op.drop_column('offer_number_prefix')

    # ### end Alembic commands ###
