"""add catalog_positions table

Revision ID: cba884fb1c2c
Revises: 311cd11f7316
Create Date: 2025-05-21 20:05:56.328976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cba884fb1c2c'
down_revision = '311cd11f7316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('vat', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalog_positions')
    # ### end Alembic commands ###
