"""Add invoice_number and due_date to invoice

Revision ID: d6b3161ceae2
Revises: 62cd2b516ba2
Create Date: 2025-05-20 20:39:35.542497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6b3161ceae2'
down_revision = '62cd2b516ba2'
branch_labels = None
depends_on = None


def upgrade():
    # Nur Änderungen an der Tabelle invoice, nicht invoice_position neu anlegen!
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_number', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('total_gross', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('total_net', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.create_unique_constraint("uq_invoice_invoice_number", ['invoice_number'])
        batch_op.drop_column('amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.FLOAT(), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_column('notes')
        batch_op.drop_column('due_date')
        batch_op.drop_column('total_net')
        batch_op.drop_column('total_gross')
        batch_op.drop_column('invoice_number')

    # ### end Alembic commands ###
